<?xml version="1.0"?>
<package format="3">
  <name>orion_hardware</name>
  <version>0.1.0</version>
  <description>ros2_control hardware interface for Orion's physical actuators.</description>

  <maintainer email="ogunbiyioladapo33@gmail.com">mofe</maintainer>
  <license>GPL-3.0-only</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>yaml_cpp_vendor</depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
