controller_manager:
  ros__parameters:
    update_rate: 100
    enforce_command_limits: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - base_yaw_joint
      - shoulder_pitch_joint
      - elbow_pitch_joint
      - head_roll_joint
      - head_pitch_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: false
    action_monitor_rate: 20.0
    constraints:
      goal_time: 0.50
      stopped_velocity_tolerance: 0.05
      base_yaw_joint:
        trajectory: 0.20
        goal: 0.05
      shoulder_pitch_joint:
        trajectory: 0.20
        goal: 0.05
      elbow_pitch_joint:
        trajectory: 0.20
        goal: 0.05
      head_roll_joint:
        trajectory: 0.20
        goal: 0.05
      head_pitch_joint:
        trajectory: 0.20
        goal: 0.05
